### ISSUE TITLE
[SUGESTÃO] Remoção de https:// no Location (QRCode Dinâmico)

### ISSUE THREAD

**Issue by joelemanoel** [hiagodotme/gpix#1]
Algum PSP pode enviar o location com "https://" e seria interessante que na hora de criar o BRCode/QRCode mesmo que passado ele fosse removido.

**Comment by hiagodotme** [comment]
Verdade @joelemanoel vou trabalhar na correção.

**Comment by hiagodotme** [comment]
@joelemanoel versão 1.0.9. Valeu =)
