### ISSUE TITLE
[Question] Any way to read return of payment? | Alguma forma de ler o retorno do pagamento?

### ISSUE THREAD

**Issue by lokize** [hiagodotme/gpix#15]
Hi is there any way to read return of payment?

-----------------------------------------------------

Existe alguma maneira de ler o retorno dos pagamentos?

**Comment by hiagodotme** [comment]
Olá @lokize, tudo bem?

Caso você utilize o `PIX.static` não será possível ler o retorno do pagamento de forma sistêmica. Para isso você deverá utilizar o `PIX.dinamic` para utilizar o PIX dinâmico é necessário ser credenciado há um PSP que utilize a API Pix oficial do Banco Central (eu atualmente trabalho com a Gerencianet, funciona muito bem e eu recomendo).

*Observação*: O PIX dinâmico, com confirmação sistêmica é cobrado.

**Comment by lokize** [comment]
Muito obrigado pela ajuda!
