### ISSUE TITLE
Is it possible to add my company logo into the pix image?

### ISSUE THREAD

**Issue by warleymendes** [hiagodotme/gpix#16]
Hi Guys,
Is it possible to add my company logo into the pix image?

Something similar to the image below:

![image](https://github.com/hiagodotme/gpix/assets/6373138/7c3b1cb0-e96f-4eba-95f3-22bf0b2cbcc9)

Thanks,
Warley

**Comment by hiagodotme** [comment]
Hello @warleymendes, how are you?

Not directly through gpix, but we use the dependency on the [qrcode](https://github.com/soldair/node-qrcode) library. If they allow it, you can change our source and make a pull request to allow this.
