### ISSUE TITLE
Está dando QR code inválido, até no seu! 

### ISSUE THREAD

**Issue by fabiobernardo** [hiagodotme/gpix#3]
### Outras Coisas!

- Faltou a função na página inicial 
**pix.isUniqueTransaction(true)**

- Faltou colocar os  tamanhos máximos de cada campo e validação pois seria bem legal

**Comment by hiagodotme** [comment]
Olá @fabiobernardo tudo bem?

Então, realmente a isUniqueTransaction não tá na doc. Sobre não funcionar, você pode falar qual PSP você está utilizando?

Inter, Nubank, BB são as instituições que possuo relacionamento. Então só fiz os testes nelas, eu ouvi uma discussão que alguns PSP's não seguiram 100% as definições para fazer o parser do brcode. Não lembro quais são.

Sobre as validações, show de bola! Assim que me sobrar um tempo eu já faço. Fique a vontade em fazer um fork tbm para ajudar na lib.

Obs: eu uso em prod e nunca tive reclamações sobre a não leitura do qrcode e possuo uma diversidade de transações ao decorrer da semana.

Valeu TmJ!

**Comment by fabiobernardo** [comment]
https://github.com/joseviniciusnunes/qrcode-pix funcionou de primeira
usei no Banco Itaú e Iti e deram código com erro

**Comment by hiagodotme** [comment]
@fabiobernardo obrigado pela informação, ou verificar com algum amigo que tenha uma conta no Itaú se ele me empresta a conta para testar.

Vou implementar as validações, obrigado pela sugestão.

**Comment by hiagodotme** [comment]
- Foi adicionado o exemplo para o `isUniqueTransaction`
- Foi implementado outras validações
- Testes atualizados: Inter, BB, Caixa, Santander, Itaú, Nubank

Versão 1.1.3 disponibilizado.
