### ISSUE TITLE
_normalizeText removendo @ em chaves do tipo email

### ISSUE THREAD

**Issue by thalesog** [hiagodotme/gpix#4]
Olá pessoal!
Notei que ao criar qrcodes estáticos, a função `_normalizeText ` está removendo o @ do email, fazendo com que o resultado seja um BRCode/QRCode inválido.

Pelo que analisei, apenas adicionando o @ no seguinte código:
Linha 82 -- lib/pix.ts
```js
return str['normalize']("NFD").replace(/[^A-Z0-9$@%*+-\./:]/gi, ' ')
```

o problema é solucionado.
@hiagodotme pode nos auxiliar nisso?

**Comment by hiagodotme** [comment]
Olá @thalesog tudo bem? Eu não testei chaves com e-mail, faz sentido o que você falou. O manual para gerar o BRCode, no item *2.1. Definições Comuns* informava os tipos de caracteres aceitos, e nele não continha o `@`, mas faz sentido ele estar nessa lista.

@thalesog se você preferir pode fazer um PR que eu mesclo a `master`, pode modificar a versão no package.json para `1.1.3` que eu já publico uma versão no NPM.

**Comment by hiagodotme** [comment]
Correção feita no PR #5

**Comment by thalesog** [comment]
@hiagodotme acabei esquecendo de trocar a versão no `package.json`, consegue ajustar para nós?
